Fix `--local` and default true for clean
cloud-bulldozer/k8s-netperf pull request #84
Opened 2023-05-26 20:50 UTC by jtaleric

### Description
Running with `--local` was borken due to missing affinity rules.

Leaving pods around makes testing quick, however can cause scheduling issues when introducing new tests. To avoid scheduling issues, we will have have the SUT be cleaned up after execution (or before).

### Fixes
Fixes #72

2023-05-30 15:51 UTC, vishnuchalla requested changes

2023-05-30 15:51 UTC, vishnuchalla commented on pkg/k8s/kubernetes.go
> +			cdpAcross.PodAntiAffinity = apiv1.PodAntiAffinity{
Looks like we have this pod antiaffinity term in both `if` and `else` clause. Can we move it outside of it if is obvious to happen irrespective of those conditions?

2023-05-30 15:51 UTC, vishnuchalla commented on pkg/k8s/kubernetes.go
> +			RequiredDuringSchedulingIgnoredDuringExecution: []apiv1.PodAffinityTerm{
Can we store this rule in some var/separate function and re-use it, as it seems to be appearing at many other places.

2023-05-30 16:06 UTC, vishnuchalla commented on pkg/k8s/kubernetes.go
> +	return false, fmt.Errorf("❌ Deployment delete issues")
Correct me if I am wrong, I don't think this statement is reachable. Because, `dw.ResultChan()` keeps on listening for the events indefinitely until the deployment is deleted. Instead we can consider a `timeout` to indicate the deployment deletion failure. But open to other thoughts too.

2023-05-30 20:35 UTC, jtaleric commented on pkg/k8s/kubernetes.go
> +func GetZones(c *kubernetes.Clientset) (string, int, error) {
Good catch, I am not even using `GetZones`

2023-05-30 23:14 UTC, jtaleric commented on pkg/k8s/kubernetes.go
> +	return false, fmt.Errorf("❌ Deployment delete issues")
` If an error occurs or Stop() is called, the implementation will close this channel and release any resources used by the watch` 

so, I will add a `TimeoutSeconds` to the `ListOptions`

2023-05-31 14:36 UTC, vishnuchalla approved these changes
Looks good to me. Thank you!

2023-05-31 14:37 UTC, merged